name: Process Completed Translations

on:
  pull_request:
    branches:
      - main
    paths:
      - 'Languages-WIP/**'

jobs:
  process-translations:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          sparse-checkout: |
            Languages/
            Languages-WIP/
            FikaLauncher/FikaLauncher/Languages/en-US/
          
      - name: Move Completed Translations
        run: |
          # Process each language directory
          for lang_dir in Languages-WIP/*/ ; do
            lang=$(basename "$lang_dir")
            
            # Check if all required files exist and are fully translated
            required_files=(
              "strings.json"
              "launcher-terms.md"
              "fika-terms.md"
            )
            
            all_files_complete=true
            for file in "${required_files[@]}"; do
              if [ ! -f "$lang_dir/$file" ]; then
                all_files_complete=false
                break
              fi
              
              # For JSON files, check completion
              if [[ $file == *.json ]]; then
                source_keys=$(jq -r 'keys | length' "FikaLauncher/FikaLauncher/Languages/en-US/$file")
                trans_keys=$(jq -r 'keys | length' "$lang_dir/$file")
                
                if [ "$source_keys" -ne "$trans_keys" ]; then
                  all_files_complete=false
                  break
                fi
              fi
            done
            
            if [ "$all_files_complete" = true ]; then
              # Move completed translations to main Languages directory
              mkdir -p "Languages/$lang"
              cp -r "$lang_dir"/* "Languages/$lang/"
            fi
          done
          
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          title: "chore: move completed translations to main"
          body: "Moving completed translations from Languages-WIP to Languages directory"
          branch: "completed-translations"
          base: "main"
          labels: |
            translations
            automated
